<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Nullable>enable</Nullable>
    <AssemblyName>HuntersArsenal</AssemblyName>
    <RootNamespace>TheHeadHunter</RootNamespace>
    <GenerateAssemblyInfo>false</GenerateAssemblyInfo>
    <Deterministic>true</Deterministic>
    <CopyLocalLockFileAssemblies>false</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="JotunnLib" Version="2.30.0" />
    <PackageReference Include="Microsoft.NETFramework.ReferenceAssemblies" Version="1.0.3" PrivateAssets="all" />
    <Reference Remove="UnityEngine.ProfilerModule" />
  </ItemGroup>

  <Target Name="DeployDebugBuild" AfterTargets="Build" Condition="'$(Configuration)' == 'Debug' and '$(MOD_DEPLOYPATH)' != ''">
    <PropertyGroup>
      <PluginDeployPath>$(MOD_DEPLOYPATH)/HuntersArsenal</PluginDeployPath>
    </PropertyGroup>
    <MakeDir Directories="$(PluginDeployPath)" />
    <Copy SourceFiles="$(TargetPath)" DestinationFolder="$(PluginDeployPath)" />
    <Copy SourceFiles="$(TargetDir)$(TargetName).pdb" DestinationFolder="$(PluginDeployPath)" Condition="Exists('$(TargetDir)$(TargetName).pdb')" />
  </Target>
</Project>